version: '2'

services:
  chainlink-request-recover-eth-usd:
    build: .
    image: inbell1s/chainlink-request-recover
    command: npm run find-missing-requests
    # restart: always
    environment:
      ORACLE_ADDRESS: '0x'
      START_BLOCK: '9150000'
      END_BLOCK: 'latest'
      RPC_URL:
      BLOCK_INTERVAL: 20000
      NODE_ADDRESS: '0x'
    volumes:
      - /data/inbell1s:/app/storage

  chainlink-request-tx:
    build: .
    image: inbell1s/chainlink-request-recover
    command: npm run fulfill-requests
    # restart: always
    environment:
      ORACLE_ADDRESS: '0x'
      RPC_URL:
      NODE_ADDRESS: '0x'
      PRIVATE_KEY: #without 0x
    volumes:
      - /data/inbell1s:/app/storage
